create initial payment model
ArtemPonomar/car-sharing-service pull request #6
Opened 2023-05-29 11:09 UTC by Skrudj

2023-05-29 11:40 UTC, ArtemGrunin approved these changes

2023-05-29 11:45 UTC, yurihhhT requested changes

2023-05-29 11:45 UTC, yurihhhT commented on src/main/java/com/example/carsharingservice/model/Payment.java
> +}
Enum should be inside class

2023-05-29 11:45 UTC, yurihhhT commented on src/main/java/com/example/carsharingservice/model/Payment.java
> +    Type type;
Better to use Integer or Long for ID
Also better to use private modification to each field

2023-05-30 07:45 UTC, ArtemPonomar approved these changes

2023-05-30 08:26 UTC, mishok321 requested changes

2023-05-30 08:26 UTC, mishok321 commented on src/main/java/com/example/carsharingservice/repository/PaymentRepository.java
> +    Payment update(Payment payment);
redunant

2023-05-30 08:26 UTC, mishok321 commented on src/main/java/com/example/carsharingservice/model/Payment.java
> +    private Long rentalId;
```suggestion
    private Long id;

```

and add foreign key

2023-05-31 08:43 UTC, mishok321 approved these changes

2023-05-31 08:48 UTC, yurihhhT approved these changes

2023-05-31 08:48 UTC, yurihhhT approved these changes

2023-05-31 08:48 UTC, yurihhhT approved these changes

2023-05-31 08:48 UTC, yurihhhT approved these changes

2023-05-31 08:48 UTC, yurihhhT approved these changes

2023-05-31 08:48 UTC, yurihhhT approved these changes
1

2023-05-31 09:00 UTC, merged